server:
  port: 8082
spring:
  application:
    name: virsical-notice
  datasource:
    url: jdbc:mysql://192.168.0.67:3306/ntc?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wafer
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 8
      filters: stat
      initial-size: 10
      filter:
        wall:
          enabled: true
          db-type: mysql
          log-violation: true
          throw-exception: true
          config:
            truncate-allow: false
            metadata-allow: true
            alter-table-allow: false
            none-base-statement-allow: false
            drop-table-allow: false
            update-where-none-check: true
            select-into-outfile-allow: false
      web-stat-filter:
        enabled: true
        principal-cookie-name: admin
        session-stat-enable: true
        url-pattern: /*
        session-stat-max-count: 100000
        exclusions: /druid/*
        profile-enable: true
        principal-session-name: admin
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 111111
        allow: 127.0.0.1
        deny: 192.168.10.1 #访问黑名单
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

# 日志文件
logging:
  file: ${user.dir}/logs/${spring.application.name}-${server.port}.log
  level:
    root: info