INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618085,'威发系统','會議通知：會議預訂成功。會議時間：{1}，會議地點：{2}，會議主題：{3}，會議鏈接： {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618086,'威发系统','會議通知：收到新的會議邀請。會議時間：{1}，會議地點：{2}，會議主題：{3}，參會鏈接： {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(2020061906,'威发系统','會議提醒：會議已被修改。會議時間：{1}，會議地點：{2}，會議主題：{3}，會議鏈接： {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618088,'威发系统','會議提醒：會議已被取消。會議時間：{1}，會議地點：{2}，會議主題：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618089,'威发系统','會議提醒：距會議開始還有{1}分鐘。會議時間：{2}，會議地點：{3}，會議主題：{4}，會議鏈接： {5}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618090,'威发系统','會議提醒：會議已開始{1}分鐘，請儘快參會。會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618091,'威发系统','會議提醒：會議即將結束。會議時間：{1}，會議地點：{2}，會議主題：{3}。延長請點擊： {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618092,'威发系统','會議提醒：會議即將結束。已無法延長，請按時完成。會議時間:{1}，會議地點：{2}，會議主題：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618093,'威发系统','會議回執：{1}同意參加會議。會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618094,'威发系统','會議回執：{1}拒絕參加會議。原因：{2}，會議時間：{3}，會議地點：{4}，會議主題：{5}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618095,'威发系统','會議申請：會議預訂申請已被批准。會議時間：{1}，會議地點：{2}，會議主題：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618096,'威发系统','會議申請：會議預訂申請已被拒絕。原因：{1}，會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618097,'威发系统','保潔提醒，{1}會議已經結束，請及時清潔','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618098,'威发系统','會議提醒：{1}被檢測到長時間處於無人狀態，會議{2}已結束','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618099,'威发系统','會議提醒：{1}被檢測到長時間處於無人狀態，會議{2}已自動結束','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618100,'威发系统','會議提醒：{1}被檢測到長時間處於無人狀態，{2}分鐘後，會議{3}將被自動結束','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618101,'威发系统','會議提醒：{1}被檢測到長時間處於無人狀態，結束會議請點擊： {2}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618102,'威发系统','會議提醒：會議因未簽到已被取消。會議時間：{1}，會議地點：{2}，會議主題：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618103,'威发系统','會議提醒：由於會議參會人名單調整，您不需要參加此次會議，如有異議，請聯系會議組織者。預訂人：{1}，會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618104,'威发系统','會議申請：{1}預訂了一個會議，需要審批。會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618105,'威发系统','報修提醒：{1}的{2}設備有人報修，請及時檢修','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618106,'威发系统','設備申請：{1}提交了一個設備申請，請及時確認。會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618107,'威发系统','服務申請：{1}提交了一個會議服務申請，請及時確認。會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618108,'威发系统','會議服務取消：有會議服務已被取消。會議時間：{1}，會議地點：{2}，會議主題：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618109,'威发系统','服務申請：會議服務申請已被批准。會議時間：{1}，會議地點：{2}，會議主題：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618110,'威发系统','服務申請：會議服務申請已被拒絕。原因：{1}，會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618111,'威发系统','會議室維護：{1}會議室將進行維護，請修改該會議。維護時間：{2}，會議時間：{3}，會議地點：{4}，會議主題：{5}，推薦會議室：{6}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618112,'威发系统','會議室維護：會議室已提前結束維護，請關注該會議。會議時間：{1}，會議地點：{2}，會議主題：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618113,'威发系统','會議室啟用：{1}會議室已啟用，請關注該會議。會議時間：{2}，會議地點：{3}，會議主題：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618114,'威发系统','會議室停用：{1}會議室已停用，請修改該會議。會議時間：{2}，會議地點：{3}，會議主題：{4}，推薦會議室：{5}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(2020061905,'威发系统','會務提醒：收到新的座位安排。會議時間：{1}，會議地點：{2}，會議主題：{3}。查看座位請點擊{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618025,'威发系统','会议通知：会议预订成功。会议时间：{1}，会议地点：{2}，会议主题：{3}，会议链接： {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(2020061826,'威发系统','会议通知：收到新的会议邀请。会议时间：{1}，会议地点：{2}，会议主题：{3}，参会链接： {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(2020061902,'威发系统','会议提醒：会议已被修改。会议时间：{1}，会议地点：{2}，会议主题：{3}，会议链接： {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618028,'威发系统','会议提醒：会议已被取消。会议时间：{1}，会议地点：{2}，会议主题：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618029,'威发系统','会议提醒：距会议开始还有{1}分钟。会议时间：{2}，会议地点：{3}，会议主题：{4}，会议链接： {5}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618030,'威发系统','会议提醒：会议已开始{1}分钟，请尽快参会。会议时间：{2}，会议地点：{3}，会议主题：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618031,'威发系统','会议提醒：会议即将结束。会议时间：{1}，会议地点：{2}，会议主题：{3}。延长请点击 {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618032,'威发系统','会议提醒：会议即将结束。已无法延长，请按时完成。会议时间:{1}，会议地点：{2}，会议主题：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618033,'威发系统','会议回执：{1}同意参加会议。会议时间：{2}，会议地点：{3}，会议主题：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618034,'威发系统','会议回执：{1}拒绝参加会议。原因：{2},会议时间：{3}，会议地点：{4}，会议主题：{5}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618035,'威发系统','会议申请：会议预订申请已被批准。会议时间：{1}，会议地点：{2}，会议主题：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618036,'威发系统','会议申请：会议预订申请已被拒绝，原因：{1}，会议时间：{2}，会议地点：{3}，会议主题：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618037,'威发系统','保洁提醒，{1}的会议已经结束，请及时清洁','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618038,'威发系统','会议提醒：{1}被检测到长时间处于无人状态，会议{2}已结束','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618039,'威发系统','会议提醒：{1}被检测到长时间处于无人状态，{2}分钟后，会议{3}将被自动结束','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618040,'威发系统','会议提醒：{1}被检测到长时间处于无人状态，会议{2}已自动结束','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618041,'威发系统','会议提醒：{1}被检测到长时间处于无人状态，结束会议请点击： {2}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618042,'威发系统','会议提醒：会议因未签到已被取消。会议时间：{1}，会议地点：{2}，会议主题：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618043,'威发系统','会议提醒：由于会议参会人名单调整，您不需要参加此次会议，如有异议，请联系会议组织者。预订人：{1}，会议时间：{2}，会议地点：{3}，会议主题：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618044,'威发系统','会议申请：{1}预订了一个会议，需要审批。会议时间：{2}，会议地点：{3}，会议主题：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618045,'威发系统','报修提醒：{1}的{2}设备有人报修，请及时检修','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618046,'威发系统','设备申请：{1}提交了一个设备申请，请及时确认。会议时间：{2}，会议地点：{3}，会议主题：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618047,'威发系统','服务申请：{1}提交了一个会议服务申请，请及时确认。会议时间：{2}，会议地点：{3}，会议主题：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618048,'威发系统','会议服务取消：有会议服务已被取消。会议时间:{1}，会议地点：{2}，会议主题：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618049,'威发系统','服务申请：会议服务申请已被批准。会议时间：{1}，会议地点：{2}，会议主题：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618050,'威发系统','服务申请：会议服务申请已被拒绝。原因：{1}，会议时间：{2}，会议地点：{3}，会议主题：{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618051,'威发系统','会议室维护：{1}会议室将进行维护，请修改该会议。维护时间：{2}，会议时间：{3}，会议地点：{4}，会议主题：{5}，推荐会议室：{6}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618052,'威发系统','会议室维护：会议室已提前结束维护，请关注该会议。会议时间：{1}，会议地点：{2}，会议主题：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618053,'威发系统','会议室启用：{1}会议室已启用，请关注该会议。会议时间：{2}，会议主题：{3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618054,'威发系统','会议室停用：{1}会议室已停用，请修改该会议。会议时间：{2}，会议地点：{3}，会议主题：{4}，推荐会议室：{5}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(2020061901,'威发系统','会务提醒：收到新的座位安排。会议时间：{1}，会议地点：{2}，会议主题：{3}。查看座位请点击{4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618055,'威发系统','Meeting Notice: You have successfully booked the meeting {1} at room {2} on {3}. For more details, please click: {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618056,'威发系统','Meeting Notice: You have an invitation to the meeting {1} at room {2} on {3}. For more details, please click: {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(2020061904,'威发系统','Meeting Reminder: Your meeting of {1} at room {2} on {3} has been modified.  For more details, please click: {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618058,'威发系统','Meeting Reminder: Your meeting of {1} at room {2} on {3} has been canceled.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618059,'威发系统','Meeting Reminder: Your meeting of {1} at room {2} will begin in {3} minutes. Please check in this meeting ASAP,  and for more details,  please click: {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618060,'威发系统','Meeting Reminder: Your meeting of {1} at room {2} has begun for {3} minutes. Please check in this meeting ASAP.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618061,'威发系统','Meeting Reminder: Your meeting {1} will be terminated on {2} as scheduled. If you want to extend the meeting, please click this url: {3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618062,'威发系统',"Meeting Reminder: Your meeting of {1} at room {2} on {3} will be terminated soon as scheduled. It can't be extended. Please finish it on time.",'','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618063,'威发系统','Meeting Receipt: {1} have accepted the invitation to the meeting of {2} at room {3} on {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618064,'威发系统','Meeting Receipt: {1} have refused the invitation to the meeting of {2} at room {3} on {4} has been rejected on the grounds that: {5}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618065,'威发系统','Meeting Application: Your meeting application has been approved, and this meeting will be held on {1} at {2} about {3} ','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618066,'威发系统','Meeting Application: Your meeting application has been rejected on the grounds that: {1}, it was originally intended to be held on {2} at {3} about {4} ','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618067,'威发系统','Cleaning Reminder: The meeting at room {1} is finished. Please clean the room in time.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618068,'威发系统','Meeting Reminder: The Sensor detected that {1} room had been idle for a long time, the meeting {2} had been terminated.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618069,'威发系统','Meeting Reminder: The Sensor detected that {1} room had been idle for a long time, the meeting {2} would be automatically terminated after {3} minutes.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618070,'威发系统','Meeting Reminder: The Sensor detected that {1} room had been idle for a long time, the meeting {2} had been automatically terminated.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618071,'威发系统','Meeting Reminder: The Sensor detected that {1} room had been idle for a long time, please terminate the meeting by clicking  {2}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618072,'威发系统','Meeting Reminder: The meeting was cancelled because no one had signed in.  Time: {1} ; Location: {2}; Subject: {3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618073,'威发系统',"Meeting Reminder: Sorry for the inconvenience. You don't have to attend the meeting due to participants adjustments . If you have any questions, please contact the meeting organizers. Host: {1}, time: {2}, room: {3}, subject: {4}",'','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618074,'威发系统','Meeting Application: You have received an application for meeting that will be held on {1} at {2} about {3}. Please check it soon and give your feedback.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618075,'威发系统','Maintenance Reminder: You have received an application for equipment maintenance about {1} in the meeting room {2}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618076,'威发系统','Device Applications: You have received an application for device that will be used at {1} at {2} about {3}. Please check it soon and give your feedback.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618077,'威发系统','Service Application: You have received an application for meeting service on {1} at {2} about {3}. Please check it soon and give your feedback.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618078,'威发系统','Meeting services canceled: Meeting service has bean cancelled on {1} at {2} about {3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618079,'威发系统','Service Application: Your application for meeting service on {1} at {2} about {3} has been approved.','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618080,'威发系统','Service Application: Your application for meeting service on {1} at {2} about {3} has been rejected on the grounds that: {4}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618081,'威发系统','Maintenance Reminder: The meeting room of {1} will be maintained on {2}. You can change your meeting {3} on {4} about {5} to meeting room {6}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618082,'威发系统','Maintenance Reminder: The maintenance of the meeting room was completed in advance. Please pay attention to your meeting {1} at room {2} on {3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618083,'威发系统','Maintenance Reminder: The meeting room {1} is available now. Please pay attention to your meeting {2} on {3}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(20200618084,'威发系统','Maintenance Reminder: The meeting room of {1} is out of service. You can change the meeting {2} on {3} about {4} to meeting room {5}','','');
INSERT INTO sms_template(id,name,content,description,category) VALUES(2020061903,'威发系统','Meeting Reminder: New seating arrangement received.  Meeting time: {1}，Location：{2}，Subject：{3}. Please click on {4} to check seating details.','','');
